apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-app
  ports:
    - protocol: 'TCP'
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  selector:
    matchLabels:
      app: user-app
  replicas: 5
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: app-1
          image: nest-microservice-user_app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
