version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    hostname: auth-service
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    networks:
      - dbnet
networks:
  dbnet:
    driver: bridge
    external: true